<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-9RQT0S6" tests="4" failures="2" timestamp="23 May 2018 14:19:21 GMT" time="25.078" errors="0">
  <testcase name="loginFail" time="6.145" classname="LoginTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at org.webdriver.patatiumwebui.utils.Assertion.VerityError(Assertion.java:1041)
	at LoginTest.loginFail(LoginTest.java:60)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- loginFail -->
  <testcase name="loginFail" time="4.518" classname="LoginTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at org.webdriver.patatiumwebui.utils.Assertion.VerityError(Assertion.java:1041)
	at LoginTest.loginFail(LoginTest.java:60)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- loginFail -->
  <testcase name="loginFail" time="3.272" classname="LoginTest"/>
  <testcase name="loginFail" time="3.29" classname="LoginTest"/>
</testsuite>
